version: "2"

services:
  node:
    build: ./docker/node
    working_dir: /www
    entrypoint: sh /entrypoint.sh
    env_file:
      - .env
    ports:
      - 29999:29999
      - 8080:8080
    volumes:
      - ./hotels/:/www
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo:5.0.3
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: db
    env_file:
      - .env
    volumes:
      - ./db:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo